kind: pipeline
name: default

steps:
  - name: build
    image: dmitriy5181/hugo
    commands:
      - hugo

  - name: publish
    image: appleboy/drone-scp
    settings:
      host: prgm.xyz
      user: pi
      key:
        from_secret: ssh_key
      rm: true
      strip_components: 1
      source: "public/*"
      target: /var/www/blog/public

  - name: notify
    image: drillster/drone-email
    settings:
      from: "Drone CI <drone@prgm.xyz>"
      host: prgm.xyz
      username:
        from_secret: email_username
      password:
        from_secret: email_password
    when:
      status:
        - failure
