kind: pipeline
name: default

steps:
  - name: build
    image: dmitriy5181/hugo
    commands:
      - hugo

  - name: publish  
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: public/
