kind: pipeline
name: default

steps:
  - name: build
    image: dmitriy5181/hugo
    volumes:
      - name: www
        path: /var/www/blog
    commands:
      - find /var/www/blog -type f -delete
      - hugo --destination /var/www/blog

  - name: notify
    image: drillster/drone-email
    settings:
      from: "Drone CI <drone@prgm.xyz>"
      host: prgm.xyz
      username:
        from_secret: email_username
      password:
        from_secret: email_password
    when:
      status:
        - success
        - failure

volumes:
- name: www
  host:
    path: /var/www/blog