baseURL = "https://blog.prgm.xyz"
title = "// pragmatic engineering"
theme = "hugo-journal"

# see https://gohugo.io/getting-started/configuration/#configure-front-matter
[frontmatter]
    date  = [":filename", ":default"]